export const FETCH_DRONE = "COMMAND/FETCH_DRONE_POSITION";

export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const WEATHER_ID_ERROR = "EVENT/WEATHER_ID_ERROR";
export const WEATHER_DATA_ERROR = "EVENT/WEATHER_DATA_ERROR";

export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
